Repository ExpediaGroup/bull, pull requests merged in 2019-07, with the labels that each got.

#74 Disable the default value set for primitive types in case they are null
  CHANGELOG-JDK8.md
  CHANGELOG.md
  README.md
  bean-utils-library/src/main/java/com/hotels/beans/transformer/AbstractTransformer.java
  bean-utils-library/src/main/java/com/hotels/beans/transformer/Transformer.java
  bean-utils-library/src/main/java/com/hotels/beans/transformer/TransformerImpl.java
  bean-utils-library/src/main/java/com/hotels/beans/transformer/TransformerSettings.java
  bean-utils-library/src/test/java/com/hotels/beans/transformer/MutableObjectTransformationTest.java
  docs/site/markdown/transformer/samples.md
Labels: enhancement

#76 Centralized Sonatype Cred Setup
  .travis.yml
  CHANGELOG.md
  config/travis/mvn-settings.xml
  pom.xml
Labels: configuration

#79 Added site icon for all browser types and applications
  docs/site/resources/images/icon/android-chrome-192x192.png
  docs/site/resources/images/icon/android-chrome-512x512.png
  docs/site/resources/images/icon/apple-touch-icon.png
  docs/site/resources/images/icon/browserconfig.xml
  docs/site/resources/images/icon/favicon-16x16.png
  docs/site/resources/images/icon/favicon-32x32.png
  docs/site/resources/images/icon/favicon.ico
  docs/site/resources/images/icon/mstile-150x150.png
  docs/site/resources/images/icon/safari-pinned-tab.svg
  docs/site/resources/images/icon/site.webmanifest
  docs/site/site.xml
Labels: documentation, enhancement

#78 Add InfoQ Brazil article translation
  docs/site/markdown/index.md
  docs/site/site.xml
Labels: documentation

#81 Feature/transformer generator module setup
  bull-transformer-generator/pom.xml
  bull-transformer-generator/transformer-bytecode-adapter/pom.xml
  bull-transformer-generator/transformer-bytecode-adapter/src/test/resources/config/logging/logback-appenders.xml
  bull-transformer-generator/transformer-bytecode-adapter/src/test/resources/config/logging/logback-properties.xml
  bull-transformer-generator/transformer-bytecode-adapter/src/test/resources/logback-test.xml
  bull-transformer-generator/transformer-bytecode-adapter/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  bull-transformer-generator/transformer-generator-core/pom.xml
  bull-transformer-generator/transformer-generator-core/src/test/resources/config/logging/logback-appenders.xml
  bull-transformer-generator/transformer-generator-core/src/test/resources/config/logging/logback-properties.xml
  bull-transformer-generator/transformer-generator-core/src/test/resources/logback-test.xml
  bull-transformer-generator/transformer-generator-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  bull-transformer-generator/transformer-registry/pom.xml
  bull-transformer-generator/transformer-registry/src/test/resources/config/logging/logback-appenders.xml
  bull-transformer-generator/transformer-registry/src/test/resources/config/logging/logback-properties.xml
  bull-transformer-generator/transformer-registry/src/test/resources/logback-test.xml
  bull-transformer-generator/transformer-registry/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  bull-transformer-generator/transformer-source-adapter/pom.xml
  bull-transformer-generator/transformer-source-adapter/src/test/resources/config/logging/logback-appenders.xml
  bull-transformer-generator/transformer-source-adapter/src/test/resources/config/logging/logback-properties.xml
  bull-transformer-generator/transformer-source-adapter/src/test/resources/logback-test.xml
  bull-transformer-generator/transformer-source-adapter/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  pom.xml
Labels: configuration, transformer bytecode, transformer core, transformer generator, transformer registry, transformer source
