Repository ExpediaGroup/bull, pull requests merged in 2019-04, with the labels that each got.

#47 Feature/gitter integration setup
  .travis.yml
  CHANGELOG.md
  README.md
Labels: documentation

#48 Feature/static transformation with given transformer
  .travis.yml
  CHANGELOG.md
  pom.xml
  src/main/java/com/hotels/beans/BeanUtils.java
  src/test/java/com/hotels/beans/BeanUtilsTest.java
Labels: enhancement

#50 Feature/map race condition
  README.md
  docs/site/markdown/transformer/samples.md
  src/main/java/com/hotels/beans/cache/CacheManagerFactory.java
  src/main/java/com/hotels/beans/utils/ClassUtils.java
  src/test/java/com/hotels/beans/utils/ClassUtilsTest.java
Labels: enhancement

#52 Fix when transformerFunction is null
  CHANGELOG.md
  src/main/java/com/hotels/beans/transformer/TransformerImpl.java
Labels: bug

#51 Feature/optional usage improvement
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  src/main/java/com/hotels/beans/base/Defaults.java
  src/main/java/com/hotels/beans/cache/CacheManager.java
  src/main/java/com/hotels/beans/transformer/TransformerImpl.java
  src/main/java/com/hotels/beans/utils/ClassUtils.java
  src/main/java/com/hotels/beans/utils/ReflectionUtils.java
  src/main/java/com/hotels/beans/utils/ValidationUtils.java
  src/test/java/com/hotels/beans/BeanUtilsTest.java
  src/test/java/com/hotels/beans/base/DefaultsTest.java
  src/test/java/com/hotels/beans/cache/CacheManagerFactoryTest.java
  src/test/java/com/hotels/beans/cache/CacheManagerTest.java
  src/test/java/com/hotels/beans/performance/PerformanceTest.java
  src/test/java/com/hotels/beans/populator/ArrayPopulatorTest.java
  src/test/java/com/hotels/beans/populator/PopulatorFactoryTest.java
  src/test/java/com/hotels/beans/transformer/ImmutableObjectTransformationTest.java
  src/test/java/com/hotels/beans/transformer/MutableObjectTransformationTest.java
  src/test/java/com/hotels/beans/utils/ClassUtilsTest.java
  src/test/java/com/hotels/beans/utils/ReflectionUtilsTest.java
  src/test/java/com/hotels/beans/utils/ValidationUtilsTest.java
Labels: enhancement

#53 Feature/builder transformation support
  CHANGELOG.md
  README.md
  docs/site/markdown/index.md
  pom.xml
  src/main/java/com/hotels/beans/cache/CacheManager.java
  src/main/java/com/hotels/beans/error/InstanceCreationException.java
  src/main/java/com/hotels/beans/populator/ArrayPopulator.java
  src/main/java/com/hotels/beans/transformer/TransformerImpl.java
  src/main/java/com/hotels/beans/utils/ClassUtils.java
  src/main/java/com/hotels/beans/utils/ReflectionUtils.java
  src/test/java/com/hotels/beans/populator/ArrayPopulatorTest.java
  src/test/java/com/hotels/beans/sample/immutable/ImmutableToFooWithBuilder.java
  src/test/java/com/hotels/beans/sample/mixed/MixedToFooMissingConstructor.java
  src/test/java/com/hotels/beans/sample/mixed/MixedToFooWithBuilder.java
  src/test/java/com/hotels/beans/sample/mutable/MutableToFooWithBuilder.java
  src/test/java/com/hotels/beans/sample/mutable/MutableToFooWithBuilderMultipleConstructor.java
  src/test/java/com/hotels/beans/transformer/BuilderObjectTransformationTest.java
  src/test/java/com/hotels/beans/transformer/ImmutableObjectTransformationTest.java
  src/test/java/com/hotels/beans/utils/ClassUtilsTest.java
  src/test/java/com/hotels/beans/utils/ReflectionUtilsTest.java
Labels: enhancement
