Repository ExpediaGroup/bull, pull requests merged in 2019-05, with the labels that each got.

#54 Setup maven wrapper
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  README.md
  mvnw
  mvnw.cmd
Labels: enhancement

#59 Feature/performance tuning
  .travis.yml
  CHANGELOG-JDK8.md
  CHANGELOG.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  docs/site/markdown/transformer/samples.md
  pom.xml
  src/main/java/com/hotels/beans/transformer/AbstractTransformer.java
  src/main/java/com/hotels/beans/transformer/Transformer.java
  src/main/java/com/hotels/beans/transformer/TransformerImpl.java
  src/main/java/com/hotels/beans/transformer/TransformerSettings.java
  src/main/java/com/hotels/beans/utils/ClassUtils.java
  src/test/java/com/hotels/beans/sample/FromFooAdvFields.java
  src/test/java/com/hotels/beans/sample/immutable/ImmutableToFooAdvFields.java
  src/test/java/com/hotels/beans/transformer/AbstractTransformerTest.java
  src/test/java/com/hotels/beans/transformer/ImmutableObjectTransformationTest.java
  src/test/java/com/hotels/beans/transformer/MutableObjectTransformationTest.java
  src/test/java/com/hotels/beans/transformer/TransformerTest.java
  src/test/java/com/hotels/beans/utils/ClassUtilsTest.java
Labels: enhancement, performance

#60 Feature/deprecated method cleanup
  .travis.yml
  BULL-BuildInstructions.txt
  CHANGELOG-JDK8.md
  CHANGELOG.md
  src/main/java/com/hotels/beans/transformer/AbstractTransformer.java
  src/main/java/com/hotels/beans/transformer/Transformer.java
  src/main/java/com/hotels/beans/utils/ReflectionUtils.java
  src/test/java/com/hotels/beans/transformer/TransformerTest.java
Labels: cleanup

#65 changed logic to pass original values to FieldTransformer
  CHANGELOG.md
  bean-utils-library/src/main/java/com/hotels/beans/transformer/TransformerImpl.java
  bean-utils-library/src/test/java/com/hotels/beans/BeanUtilsTest.java
  bean-utils-library/src/test/java/com/hotels/beans/transformer/ImmutableObjectTransformationTest.java
  bull-common/src/test/java/com/hotels/beans/sample/FromFooSimpleBooleanField.java
  bull-common/src/test/java/com/hotels/beans/sample/immutable/ImmutableToFooSimpleBoolean.java
Labels: bug

#63 Feature/supplier transformation
  CHANGELOG-JDK8.md
  CHANGELOG.md
  README.md
  bean-utils-library/pom.xml
  bean-utils-library/src/main/java/com/hotels/beans/model/FieldTransformer.java
  bean-utils-library/src/main/java/com/hotels/beans/transformer/AbstractTransformer.java
  bean-utils-library/src/main/java/com/hotels/beans/transformer/TransformerImpl.java
  bean-utils-library/src/main/java/com/hotels/beans/transformer/TransformerSettings.java
  bean-utils-library/src/test/java/com/hotels/beans/BeanUtilsTest.java
  bean-utils-library/src/test/java/com/hotels/beans/transformer/ImmutableObjectTransformationTest.java
  bean-utils-library/src/test/java/com/hotels/beans/transformer/MutableObjectTransformationTest.java
  bull-common/src/test/java/com/hotels/beans/sample/FromFooSimpleBooleanField.java
  bull-common/src/test/java/com/hotels/beans/sample/immutable/ImmutableToFooSimpleBoolean.java
  bull-common/src/test/resources/config/logging/logback-appenders.xml
  bull-common/src/test/resources/config/logging/logback-properties.xml
  bull-common/src/test/resources/logback-test.xml
  docs/site/markdown/transformer/samples.md
  pom.xml
Labels: enhancement
